# SPDX-FileCopyrightText: Copyright (c) 2014-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT

version = 1
[[annotations]]
path = [
    ".DS_Store",
    ".gitattributes",
    ".gitignore",
    ".latexmkrc",
    ".pdd",
    ".texsc",
    "**.dat",
    "**.eot",
    "**.gif",
    "**.gpi",
    "**.html",
    "**.ico",
    "**.jar",
    "**.jpg",
    "**.json",
    "**.liquid",
    "**.md",
    "**.pdf",
    "**.png",
    "**.svg",
    "**.ttf",
    "**.txt",
    "**.woff",
    "**.woff2",
    "**.zip",
    "**/.DS_Store",
    "**/.gitignore",
    "**/.latexmkrc",
    "**/.pdd",
    "**/.texsc",
    "**/*.csv",
    "**/*.jpg",
    "**/*.json",
    "**/*.pdf",
    "**/*.png",
    "**/*.svg",
    "**/*.txt",
    "**/*.vm",
    "**/aspell.en.pws",
    "**/CNAME",
    "**/Gemfile.lock",
    "**/README.md",
    "aspell.en.pws",
    "CNAME",
    "Gemfile.lock",
    "README.md",
    "renovate.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2014-2026 Yegor Bugayenko"
SPDX-License-Identifier = "MIT"
